spring.application.name=biblio-centrale
server.servlet.context-path=/bibliocentrale
server.port=8094

#DATABASE CONFIG

# Custom H2 Console URL
spring.h2.console.enabled=true
spring.h2.console.path=/h2
#Acces à la console BDD H2: http://localhost:8094/bibliocentrale/h2/

spring.datasource.url=jdbc:h2:mem:bibliocentrale_db
#spring.datasource.url=jdbc:h2:file:C:/h2/data/bibliocentrale_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Gestion des logs
#Source: https://www.baeldung.com/sql-logging-spring-boot

#logs the SQL queries
logging.level.org.hibernate.SQL=DEBUG
#logs the prepared statement parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Permet d'afficher les paramètres d'une requête sql
logging.level.org.hibernate.orm.jdbc.bind=TRACE


#SECURITY
#CONGITO AWS LOGIN
#LOGIN/PASS=bnguimgo@yahoo.fr/Nguibert123*

#COGNITO ON POSTMAN
#LOGIN/PASS=bnguimgo/Nguibert123*

